#pragma once
// AUTO-GENERATED by tools/embed_manifest.py from the MIDL submodule. Do not edit.
// Source: midl/schemas/gen/yb-midl-capabilities.square-480.json
//
// These are the firmware projection bounds for the build's display class,
// parsed from the SAME capability JSON that is served verbatim via
// generated_midl_manifest.h. include/midl_limits.h consumes them so the
// solver/arena/freeform fixed-array sizes and the advertised manifest can
// never silently diverge. Regenerate with `make embed-manifest`.
namespace midl_gen {
inline constexpr const char *CLASS_ID = "square-480";
inline constexpr int MAX_TILES = 9;
inline constexpr int MAX_DEPTH = 3;
}  // namespace midl_gen
