#pragma once

// Single source of truth for the firmware-facing MIDL projection bounds.
// These mirror the layout POD limits (include/layout.h) and the values the
// square-480 capability manifest advertises. Plan 6's parser/solver and the
// host guard tests both read them from here so a POD change and a manifest
// change cannot silently diverge.

#include <stddef.h>

#include "generated_midl_limits.h"  // midl_gen::MAX_TILES / MAX_DEPTH (from the capability spec)
#include "layout.h"                 // layout::MAX_SCREENS, STR_LEN, PATH_LEN

namespace midl {

// Maximum nesting depth of a layout node tree the firmware solver will walk.
// DERIVED FROM THE CAPABILITY SPEC (midl_gen::MAX_DEPTH, generated by
// tools/embed_manifest.py from the build's display-class JSON). Enforced AS the
// solver descends (a post-hoc depth check would already have overflowed the
// 8 KB task stack — CLAUDE.md silent-reboot trap), so it is a hard recursion
// bound, not advice. Use midl::MAX_LAYOUT_DEPTH as the solver recursion guard
// (stops descent); use FirmwareLimits::max_depth for cross-layer comparisons.
// Both resolve to the same constexpr value.
constexpr int MAX_LAYOUT_DEPTH = midl_gen::MAX_DEPTH;

// A resolved single-class projection the device accepts must fit all of these.
//
// max_tiles_per_screen / max_depth come from the capability spec (midl_gen::*,
// generated from midl/schemas/gen/yb-midl-capabilities.<class>.json) so the
// firmware's fixed-array bounds and the advertised/validated manifest share ONE
// source of truth. This is INTENTIONALLY DECOUPLED from the legacy
// layout::MAX_TILES_PER_SCREEN (still 4): the legacy layout::Config POD is guarded
// to <=48 KB (test_midl_projection), and raising its tile count would blow that
// guard. The MIDL render path (solver PlacementSet, MidlScreenArena, freeform
// tiles) sizes from here instead.
struct FirmwareLimits {
    static constexpr size_t max_screens = layout::MAX_SCREENS;           // 8
    static constexpr size_t max_tiles_per_screen = midl_gen::MAX_TILES;  // spec-derived (9)
    static constexpr int max_depth = MAX_LAYOUT_DEPTH;                   // spec-derived (3)
    static constexpr size_t str_len = layout::STR_LEN;                   // 32 (incl NUL)
    static constexpr size_t path_len = layout::PATH_LEN;                 // 96 (incl NUL)
};

// Compile-time footprint budgets for the MIDL render path (Part B). The arena
// pool lives in PSRAM (abundant — 8 MB); the per-screen FreeformState (which
// holds tiles[max_tiles_per_screen]) is the structure that grows with the tile
// count. static_asserts next to each struct (midl_render_apply.cpp, ui_layouts.cpp)
// hold the configured-count footprint under these caps so an over-large limit
// fails the BUILD, not the device. Generous headroom; tune if a class needs more.
constexpr size_t MIDL_ARENA_PSRAM_BUDGET = 96 * 1024;  // whole arena pool (ui::MAX_SCREENS arenas)
constexpr size_t MIDL_FREEFORM_STATE_BUDGET = 8 * 1024;  // one per-screen FreeformState

}  // namespace midl
