#!/usr/bin/env python3
"""Embed a MIDL capabilities manifest JSON into a C++ header for flash storage.

Usage:
    python3 tools/embed_manifest.py [class-id]

    class-id: one of square-480 (default), landscape-800x480, landscape-1024x600

Writes two headers, both AUTO-GENERATED from the same per-class capability JSON
(midl/schemas/gen/yb-midl-capabilities.<class>.json) so they cannot drift:

  include/generated_midl_manifest.h
      constexpr const char* of the verbatim JSON, served from a web handler
      without any heap allocation.

  include/generated_midl_limits.h
      constexpr ints (maxTiles, maxDepth) parsed from the JSON's class entry,
      consumed by include/midl_limits.h so the firmware's fixed-array bounds
      (solver PlacementSet, MIDL arena, freeform tiles) are driven by the SAME
      spec the manager validates against. Single source of truth.
"""

import json
import sys
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

VALID_CLASSES = ("square-480", "landscape-800x480", "landscape-1024x600")

def main():
    class_id = sys.argv[1] if len(sys.argv) > 1 else "square-480"
    if class_id not in VALID_CLASSES:
        print(f"ERROR: unknown class '{class_id}'. Valid: {', '.join(VALID_CLASSES)}", file=sys.stderr)
        sys.exit(1)

    src = os.path.join(REPO_ROOT, "midl", "schemas", "gen",
                       f"yb-midl-capabilities.{class_id}.json")
    dst = os.path.join(REPO_ROOT, "include", "generated_midl_manifest.h")

    if not os.path.isfile(src):
        print(f"ERROR: source not found: {src}", file=sys.stderr)
        sys.exit(1)

    with open(src, "r", encoding="utf-8") as f:
        json_text = f.read()

    # Safety check: the raw-string delimiter must not appear in the payload.
    delimiter = "midljson"
    if delimiter in json_text:
        print(f"ERROR: delimiter '{delimiter}' found inside JSON — choose a different delimiter",
              file=sys.stderr)
        sys.exit(1)

    header = f"""\
#pragma once
// AUTO-GENERATED by tools/embed_manifest.py from the MIDL submodule. Do not edit.
// Source: midl/schemas/gen/yb-midl-capabilities.{class_id}.json
namespace midl_manifest {{
inline constexpr const char *CLASS_ID = "{class_id}";
inline constexpr const char *JSON = R"{delimiter}({json_text}){delimiter}";
}}  // namespace midl_manifest
"""

    with open(dst, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"Wrote {dst}  ({len(json_text)} bytes of JSON, class={class_id})")

    # --- Second artifact: parse the class entry and emit the firmware limits. ---
    manifest = json.loads(json_text)
    classes = manifest.get("classes", [])
    cls = next((c for c in classes if c.get("id") == class_id), classes[0] if classes else None)
    if cls is None:
        print(f"ERROR: no class entry in {src}", file=sys.stderr)
        sys.exit(1)
    max_tiles = int(cls["maxTiles"])
    max_depth = int(cls["maxDepth"])

    limits_dst = os.path.join(REPO_ROOT, "include", "generated_midl_limits.h")
    limits_header = f"""\
#pragma once
// AUTO-GENERATED by tools/embed_manifest.py from the MIDL submodule. Do not edit.
// Source: midl/schemas/gen/yb-midl-capabilities.{class_id}.json
//
// These are the firmware projection bounds for the build's display class,
// parsed from the SAME capability JSON that is served verbatim via
// generated_midl_manifest.h. include/midl_limits.h consumes them so the
// solver/arena/freeform fixed-array sizes and the advertised manifest can
// never silently diverge. Regenerate with `make embed-manifest`.
namespace midl_gen {{
inline constexpr const char *CLASS_ID = "{class_id}";
inline constexpr int MAX_TILES = {max_tiles};
inline constexpr int MAX_DEPTH = {max_depth};
}}  // namespace midl_gen
"""

    with open(limits_dst, "w", encoding="utf-8") as f:
        f.write(limits_header)

    print(f"Wrote {limits_dst}  (class={class_id} maxTiles={max_tiles} maxDepth={max_depth})")


if __name__ == "__main__":
    main()
