#!/usr/bin/env python3
"""Embed a MIDL capabilities manifest JSON into a C++ header for flash storage.

Usage:
    python3 tools/embed_manifest.py [class-id]

    class-id: one of square-480 (default), landscape-800x480, landscape-1024x600

Writes include/generated_midl_manifest.h containing a constexpr const char*
holding the verbatim JSON, suitable for direct serving from a web handler
without any heap allocation.
"""

import sys
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

VALID_CLASSES = ("square-480", "landscape-800x480", "landscape-1024x600")

def main():
    class_id = sys.argv[1] if len(sys.argv) > 1 else "square-480"
    if class_id not in VALID_CLASSES:
        print(f"ERROR: unknown class '{class_id}'. Valid: {', '.join(VALID_CLASSES)}", file=sys.stderr)
        sys.exit(1)

    src = os.path.join(REPO_ROOT, "midl", "schemas", "gen",
                       f"yb-midl-capabilities.{class_id}.json")
    dst = os.path.join(REPO_ROOT, "include", "generated_midl_manifest.h")

    if not os.path.isfile(src):
        print(f"ERROR: source not found: {src}", file=sys.stderr)
        sys.exit(1)

    with open(src, "r", encoding="utf-8") as f:
        json_text = f.read()

    # Safety check: the raw-string delimiter must not appear in the payload.
    delimiter = "midljson"
    if delimiter in json_text:
        print(f"ERROR: delimiter '{delimiter}' found inside JSON — choose a different delimiter",
              file=sys.stderr)
        sys.exit(1)

    header = f"""\
#pragma once
// AUTO-GENERATED by tools/embed_manifest.py from the MIDL submodule. Do not edit.
// Source: midl/schemas/gen/yb-midl-capabilities.{class_id}.json
namespace midl_manifest {{
inline constexpr const char *CLASS_ID = "{class_id}";
inline constexpr const char *JSON = R"{delimiter}({json_text}){delimiter}";
}}  // namespace midl_manifest
"""

    with open(dst, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"Wrote {dst}  ({len(json_text)} bytes of JSON, class={class_id})")


if __name__ == "__main__":
    main()
