Import("env")

import datetime
import os
import re
import subprocess
from pathlib import Path


ROOT = Path(env["PROJECT_DIR"])
VERSION_FILE = ROOT / "VERSION"
GENERATED_HEADER = ROOT / "include" / "build_version.h"
SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$")


def read_version_file():
    version = VERSION_FILE.read_text(encoding="utf-8").strip()
    if not SEMVER_RE.match(version):
        raise ValueError(f"invalid VERSION '{version}'")
    return version


def git_output(args, fallback=""):
    """Run git, return stripped stdout. fallback on any failure or empty."""
    try:
        out = subprocess.check_output(
            ["git", *args],
            cwd=str(ROOT),
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        return out or fallback
    except Exception:
        return fallback


def compute_version(base):
    """Return (full_version_string, source_label).

    Rules (first match wins):
      1. `ESPDISP_VERSION` env override (CI release path) - take verbatim.
      2. Current HEAD is exactly the tag `v<base>` - return bare `base`.
         This is what the tag-triggered release build produces.
      3. Repo has a history - return `<base>+<N>.g<sha>[.dirty]` where N
         is `git rev-list --count v<base>..HEAD` (commits past the
         release tag) when that tag exists, else total commit count.
      4. Not a git checkout - return `<base>+local`.
    """
    env_override = os.environ.get("ESPDISP_VERSION", "").strip()
    if env_override:
        if not SEMVER_RE.match(env_override):
            raise ValueError(f"invalid ESPDISP_VERSION '{env_override}'")
        return env_override, "env"

    sha = git_output(["rev-parse", "--short=12", "HEAD"])
    if not sha:
        return f"{base}+local", "no-git"

    # Are we sitting exactly on the v<base> tag?
    head_tag = git_output(["tag", "--points-at", "HEAD"])
    tag_name = f"v{base}"
    if tag_name in head_tag.splitlines():
        return base, "on-tag"

    # How many commits past the v<base> tag are we?
    ahead = git_output(["rev-list", "--count", f"{tag_name}..HEAD"])
    if not ahead:
        # Tag doesn't exist yet (pre-first-release). Use total commits.
        ahead = git_output(["rev-list", "--count", "HEAD"], "0")

    dirty = "" if git_output(["status", "--porcelain"]) == "" else ".dirty"
    return f"{base}+{ahead}.g{sha}{dirty}", "dev"


base_version = read_version_file()
version, version_source = compute_version(base_version)

commit = git_output(["rev-parse", "--short=12", "HEAD"], "unknown")
# CI sets GITHUB_SHA; that's the authoritative ref when present and avoids
# a `git` subprocess on the runner. Trim to 12 chars to match the local path.
github_sha = os.environ.get("GITHUB_SHA", "").strip()
if github_sha and re.fullmatch(r"[0-9a-fA-F]+", github_sha):
    commit = github_sha[:12]

build_iso = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# Generate include/build_version.h. Keep it stable when nothing changed
# so we don't trigger spurious rebuilds.
header_body = f"""// Auto-generated by tools/version.py. Do not edit; do not commit.
// Regenerated on every `pio run`. Listed in .gitignore.

#pragma once

#define FW_NAME            "espdisp"
#define FW_VERSION         "{version}"
#define FW_BASE_VERSION    "{base_version}"
#define FW_VERSION_SOURCE  "{version_source}"
#define FW_GIT_COMMIT      "{commit}"
#define FW_BUILD_ISO       "{build_iso}"
#define PIO_ENV            "{env['PIOENV']}"
"""
prev = GENERATED_HEADER.read_text(encoding="utf-8") if GENERATED_HEADER.exists() else ""
if prev != header_body:
    GENERATED_HEADER.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_HEADER.write_text(header_body, encoding="utf-8")

# Sidecar artifact next to the binary so you can `cat .pio/build/<env>/firmware-version.txt`
# without booting the device. Includes everything needed to identify a
# build long after it has shipped (version string + commit + ISO time).
build_dir = Path(env.subst("$BUILD_DIR"))
build_dir.mkdir(parents=True, exist_ok=True)
sidecar = build_dir / "firmware-version.txt"
sidecar.write_text(
    f"version={version}\n"
    f"base_version={base_version}\n"
    f"version_source={version_source}\n"
    f"git_commit={commit}\n"
    f"build_iso={build_iso}\n"
    f"pio_env={env['PIOENV']}\n",
    encoding="utf-8",
)

# Keep the legacy CPPDEFINES for any TU still using -D values directly.
# build_version.h is the canonical source going forward; new code should
# `#include "build_version.h"` instead of relying on macros from the
# build flags (rebuilds are quicker when only the header changes).
env.Append(
    CPPDEFINES=[
        ("FW_NAME", env.StringifyMacro("espdisp")),
        ("FW_VERSION", env.StringifyMacro(version)),
        ("FW_BASE_VERSION", env.StringifyMacro(base_version)),
        ("FW_GIT_COMMIT", env.StringifyMacro(commit)),
        ("PIO_ENV", env.StringifyMacro(env["PIOENV"])),
    ]
)

print(f"espdisp version: {version} (base={base_version}, source={version_source}, commit={commit})")
