#!/usr/bin/env python3
"""Generate include/secrets.h from environment variables.

The generated file is intentionally gitignored. CI/release workflows use this
instead of committing secrets or relying on shell quoting for C string literals.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path


def c_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def env(name: str, default: str = "") -> str:
    return os.environ.get(name, default)


def integer_macro(name: str, default: str) -> str:
    value = env(name, default)
    if not value.isdecimal():
        raise SystemExit(f"{name} must be an integer")
    return value


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate include/secrets.h")
    parser.add_argument("--output", default="include/secrets.h")
    parser.add_argument(
        "--require-ota-password",
        action="store_true",
        help="fail if YEYBOATS_OTA_PASSWORD is empty",
    )
    args = parser.parse_args()

    ota_password = env("YEYBOATS_OTA_PASSWORD")
    if args.require_ota_password and not ota_password:
        raise SystemExit("YEYBOATS_OTA_PASSWORD is required for this build")

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "\n".join(
            [
                "#pragma once",
                "",
                "// Generated by tools/write_secrets_header.py.",
                "// Do not commit this file.",
                "",
                f"#define WIFI_SSID  {c_string(env('YEYBOATS_WIFI_SSID'))}",
                f"#define WIFI_PASS  {c_string(env('YEYBOATS_WIFI_PASS'))}",
                f"#define OTA_HOSTNAME  {c_string(env('YEYBOATS_OTA_HOSTNAME', 'yey-d'))}",
                f"#define OTA_PASSWORD  {c_string(ota_password)}",
                f"#define UDP_LOG_PORT {integer_macro('YEYBOATS_UDP_LOG_PORT', '9999')}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    if ota_password:
        print(f"wrote {output} with OTA password set")
    else:
        print(f"wrote {output} with empty OTA password")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
