require('./plugin.test')
require('./firmware-contract.test')
require('./mock-firmware.test')
require('./display-widgets.test')
require('./dashboard.test')
require('./discovery.test')
console.log('espdisp-manager test suite passed')
