require('./plugin.test')
require('./firmware-contract.test')
require('./mock-firmware.test')
require('./display-widgets.test')
require('./dashboard.test')
require('./discovery.test')
require('./webapp-metadata.test')
require('./app-dock-config.test')
require('./ui-config-widget.test')
require('./dashboard-import-export.test')
console.log('espdisp-manager test suite passed')
