const assert = require('assert')
const fs = require('fs')
const path = require('path')

const source = fs.readFileSync(path.join(__dirname, '..', 'index.js'), 'utf8')

assert.ok(source.includes('function renderDeviceConfigWidget'), 'device config widget renderer is missing')
assert.ok(source.includes('function renderDeviceConfigForm'), 'device config form renderer is missing')
assert.ok(source.includes("value=\"save-send\""), 'save-and-send device action is missing')
assert.ok(source.includes("value=\"save-preset\""), 'save-as-preset action is missing')
assert.ok(source.includes("type: 'config.reload'"), 'config reload command is not queued by UI saves')
assert.ok(source.includes("router.post('/ui/devices/:id/config'"), 'device config form route is missing')
assert.ok(source.includes("router.get('/ui/devices/:id/live/status'"), 'live status UI route is missing')
assert.ok(source.includes("router.get('/ui/devices/:id/live/logs'"), 'live logs UI route is missing')
assert.ok(source.includes("router.post('/devices/register-from-signalk'"), 'SignalK-side registration route is missing')
assert.ok(source.includes("router.get('/ui/profiles/:id'"), 'preset detail route is missing')
assert.ok(source.includes("router.post('/ui/profiles/:id/apply'"), 'preset apply route is missing')
assert.ok(source.includes('function parseUrlEncodedForm'), 'multi-select form parser is missing')
assert.ok(source.includes('Apply to selected devices'), 'multi-device preset apply UI is missing')
assert.ok(source.includes('Resolve ${escapeHtml(blocked.join'), 'unsafe discovered-device claim guard is missing')
assert.ok(source.includes('button[disabled]'), 'disabled claim button styling is missing')
assert.ok(source.includes('renderWidgetsTable(config.widgets)'), 'widget summary table is not rendered')
assert.ok(source.includes('renderScreensTable(config.layout, views)'), 'screen layout table is not rendered')
assert.ok(source.includes('SignalK and NMEA'), 'data source section is not rendered')
assert.ok(source.includes('Live status</a>'), 'live status widget link is missing')
assert.ok(source.includes('Live logs</a>'), 'live logs widget link is missing')
assert.ok(source.includes('Scan network'), 'discovery scan form is not rendered')
assert.ok(source.includes('>Scan</button>'), 'discovery scan button is missing')
assert.ok(source.includes('>Refresh</a>'), 'discovery refresh link is missing')
assert.ok(source.includes('/plugins/espdisp-manager/ui/devices">Refresh</a>'), 'devices refresh link is missing')
assert.ok(source.includes('Register through SignalK'), 'SignalK-side registration form is missing')
assert.ok(source.includes('sendManagerRegister'), 'device manager-register form option is missing')
assert.ok(source.includes('Device upgrade status'), 'firmware upgrade status table is missing')
assert.ok(source.includes('Refresh catalog from GitHub'), 'firmware GitHub refresh control is missing')
assert.ok(source.includes("router.post('/ui/firmware/catalog/refresh'"), 'firmware catalog UI refresh route is missing')
assert.ok(source.includes("router.post('/ui/devices/:id/firmware/update'"), 'firmware update UI route is missing')
assert.ok(source.includes('Queue update ${escapeHtml'), 'firmware queue update button is missing')
assert.ok(source.includes('function firmwareSourceLabel'), 'firmware source labels are missing')
assert.ok(source.includes('fs.createReadStream(file.path)'), 'SignalK firmware binary download stream is missing')
assert.ok(!source.includes('JSON.stringify(config'), 'device config UI must not render raw JSON')
assert.ok(!source.includes('Generated config preview'), 'device page must not label a raw config preview')
